//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostavka
    {
        public int Shipper { get; set; }
        public string Product { get; set; }
        public System.DateTime DateDostavki { get; set; }
        public int Kolichestvo { get; set; }
    
        public virtual Furnityra Furnityra { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Shipper Shipper1 { get; set; }
    }
}
