//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_specification
    {
        public string Marking { get; set; }
        public string Specification_name { get; set; }
        public string Specification_value { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
