//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FurnitureShopEntitie : DbContext
    {
        public FurnitureShopEntitie()
            : base("name=FurnitureShopEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Edinica_izmerenia> Edinica_izmerenia { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Equipment_specification> Equipment_specification { get; set; }
        public virtual DbSet<Equipment_type> Equipment_type { get; set; }
        public virtual DbSet<Furnityra> Furnityra { get; set; }
        public virtual DbSet<GOST> GOST { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Operation_specification> Operation_specification { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_detail> Order_detail { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Shipper> Shipper { get; set; }
        public virtual DbSet<Specification_furniture> Specification_furniture { get; set; }
        public virtual DbSet<Specification_material> Specification_material { get; set; }
        public virtual DbSet<Specification_sborochnay_edinica> Specification_sborochnay_edinica { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_complectyushih> Type_complectyushih { get; set; }
        public virtual DbSet<Type_material> Type_material { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Quality> Quality { get; set; }
    }
}
